[options]
bootstrap_before = "myspacevim#before"

[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30
default_shell = 'terminal'
[[layers]]
name = 'checkers'
lint_on_the_fly =true
[[layers]]
name ='git'
[[layers]]
name = "lang#c"
  [layer.clang_std]
    c = "c11"
    cpp = "c++1z"
    objc = "c11"
    objcpp = "c++1z"
[[layers]]
name = "tags"
[[layers]]
name = "ui"